apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: general-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shiba
  minReplicas: 1
  maxReplicas: 30
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Pods
        value: 4
        periodSeconds: 2
      - type: Percent
        value: 100
        periodSeconds: 2 
    scaleDown:
      stabilizationWindowSeconds: 0
      policies:
      - type: Pods
        value: 4
        periodSeconds: 2
      - type: Percent
        value: 100
        periodSeconds: 2


