apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
   app: guestbook
   tier: front-1
spec:
  replicas: 5
  selector:
    matchLabels:
      tier: front-1
  template:
    metadata:
      labels:
        tier: front-1
    spec:
      containers:
      - name: php-redis
        ### image: localhost:5000/php-redis
        image: localhost:5000/ubuntu
        command: ["sleep", "120"]
        imagePullPolicy: IfNotPresent

