apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    tier: front-1
spec:
  containers:
  - name: hello1
    image: localhost:5000/ubuntu:latest
    command: ["sleep", "120"]
    imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    tier: front-1
spec:
  containers:
  - name: hello2
    image: localhost:5000/ubuntu:latest
    command: ["sleep", "120"]
    imagePullPolicy: IfNotPresent
